name: Update OpenAPI Schema

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Test mode (no commits or PRs will be created)'
        required: false
        default: false
        type: boolean
  schedule:
    # Midnight UTC every weekday
    - cron: '0 0 * * 1-5'

jobs:
  update-schema:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.DOCUMENTATION_AUTOMATION_AGENT_ID }}
          private-key: ${{ secrets.DOCUMENTATION_AUTOMATION_AGENT_PRIVATE_KEY }}

      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Fetch OpenAPI Schema
        run: |
          curl -s https://api.elevenlabs.io/openapi.json > ./fern/apis/api/openapi.json

      - name: Format OpenAPI Schema
        run: |
          pnpm install
          pnpm run fmt:openapi

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          DRY_RUN: ${{ inputs.dryRun }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Set up git config regardless of dry run mode
          git add ./fern/apis/api/openapi.json

          # Check for changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          # In dry run mode, just show what would be committed
          if [ "$DRY_RUN" = "true" ]; then
            echo "DRY RUN: Changes detected (showing first 20 lines):"
            git diff --staged | head -n 20
            echo "... (more changes not shown) ..."
            exit 0
          fi

          git commit -m "Update OpenAPI schema from api.elevenlabs.io"
          git push
